# Essential ESPHome config options
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: "2023.12.0"
  on_boot:
    then:
      # Wakes up the desk and reports height
      - uart.write:
          id: controlbox
          data: [ 0xAA, 0xFF, 0x00, 0x50, 0x2B, 0x08 ]
  project:
    name: tj_horner.upsy_desky
    version: "2.0.0"

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome_components
      ref: master
    components: [ uart_mitm ]
    refresh: 0s
    
uart_mitm:
  uart1: keypad
  uart2: controlbox

uart:
 - id: keypad
   rx_pin: 19
   tx_pin: 18
   baud_rate: 19200
 - id: controlbox
   rx_pin: 17
   tx_pin: 16
   baud_rate: 19200
  
esp32:
  board: esp32dev

# Configurable options
substitutions:
  name: "upsy-desky"
  friendly_name: "Upsy Desky"
  desk_height_name: "Desk Height"
  target_desk_height_name: "Target Desk Height" 
  
  # Standing Desk Component Config
  standing_desk_min_height: "61"
  standing_desk_max_height: "126"

  # Runtime Config Defaults
  default_height_units: "cm" # Must be "in" or "cm"

packages:
  standing_desk:
    url: https://github.com/scholzri/esphome-standing-desk
    ref: master
    file: configs/template.yaml
    refresh: 0s
  addon_presets: !include addons/presets.yaml
  addon_stable_ids: !include addons/stable-ids.yaml
  addon_runtime_config: !include addons/runtime-config.yaml

button:
  - platform: restart
    name: "Restart"

light:
  - platform: status_led
    id: upsy_desky_status_led
    name: "Status LED"
    pin: GPIO23
    restore_mode: RESTORE_DEFAULT_ON
